### ISSUE TITLE
How to enable 2nd master i2c via P8_0 and P8_1 ?

### ISSUE THREAD

**Issue by ubntpeter** [Infineon/mbed-os-example-emwin-oled#4]
Hi Cypress :

After build this example , we can access i2c devices via P6_0 and P6_1.
Because we have many i2c devices on psoc ,  we have to use 2nd i2c master.
could you show us how to enable 2nd master i2c via P8_0 and P8_1 on mbed?
Thanks

**Comment by cy-vaira** [comment]
Hi @ubntpeter, 

You can instantiate a 2nd I2C master connection with the following code. 

`
I2C i2c_master(P8_1, P8_0);
i2c_master.frequency(400000);
`
Please see the example on this page to learn how to use the I2C master API. 
https://os.mbed.com/docs/mbed-os/v5.14/apis/i2c.html

**Comment by ubntpeter** [comment]
Hi Cypress:

we add
I2C i2c_master(P8_1, P8_0);   
i2c_master.frequency(400000);
i2c_master.write(i2c_addr<<1, pData, numBytes, false);
i2c_master.read(i2c_addr<<1, pData, numBytes, false);

But the P8_0 and P8_1 were still low ,  did not have any I2c signal .

**Comment by cy-vaira** [comment]
Hi, 

Which kit are you using? Is it Cypress kit or your own board? can you confirm if you have pull-up resistors connected externally on the I2C lines?

**Comment by ubntpeter** [comment]
we found the problem.   2nd Master I2c work .     

1. Cy_GPIO_Pin_Init(SE_SCL_PORT, SE_SCL_PIN, &CYBSP_SE_SCL_config);
Cy_GPIO_Pin_Init(SE_SDA_PORT, SE_SDA_PIN, &CYBSP_SE_SDA_config);

2. short R64 and R172 on wifi bt pioneer kit .


Thanks,  you can close this issue.

**Comment by cy-vaira** [comment]
Thanks. Kindly requesting you to use https://community.cypress.com for help with general questions and use GitHub for reporting bugs.
